FROM node:18-alpine as build
WORKDIR /app
COPY ./ /app/
RUN npm install --force
RUN npm run build --base-href
FROM nginx:alpine
COPY --from=build /app/dist/detectead /usr/share/nginx/html
RUN cd /usr/share/nginx/html
RUN rm -rf index.html
RUN mv /usr/share/nginx/html/browser/* /usr/share/nginx/html/
EXPOSE 80